# Spark 默认配置
spark.master                    spark://spark-master:7077
spark.driver.memory             1g
spark.executor.memory           1g
spark.executor.cores            1

# 事件日志（可选，用于 History Server）
spark.eventLog.enabled          false
spark.eventLog.dir              /opt/spark-events

# SQL 仓库目录
spark.sql.warehouse.dir         /opt/spark-warehouse

# 序列化
spark.serializer                org.apache.spark.serializer.KryoSerializer

# 日志级别
spark.logConf                   true
